name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout kod sa Git-a
      uses: actions/checkout@v4
    
    - name: Set Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint check
      run: npm run lint

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run all Playwright tests
      run: npx playwright test
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Set up GitHub Pages environment
      uses: actions/configure-pages@v4
      if: ${{ !cancelled() }}

    - name: Zip Playwright report folder
      uses: actions/upload-pages-artifact@v3
      if: ${{ !cancelled() }}
      with:
        path: playwright-report/

  # OVAJ DEO KODA IZBACUJE PLAVI LINK NA GLAVNI EKRAN
  deploy:
    needs: test
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
